///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CommonLib
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CommonLibRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("ea57afbf-3d64-4c9b-9d71-8b6953a60fce")]
    public partial class CommonLibRepository : RepoGenBaseFolder
    {
        static CommonLibRepository instance = new CommonLibRepository();

        /// <summary>
        /// Gets the singleton class instance representing the CommonLibRepository element repository.
        /// </summary>
        [RepositoryFolder("ea57afbf-3d64-4c9b-9d71-8b6953a60fce")]
        public static CommonLibRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CommonLibRepository() 
            : base("CommonLibRepository", "/", null, 0, false, "ea57afbf-3d64-4c9b-9d71-8b6953a60fce", ".\\RepositoryImages\\CommonLibRepositoryea57afbf.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ea57afbf-3d64-4c9b-9d71-8b6953a60fce")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class CommonLibRepositoryFolders
    {
    }
#pragma warning restore 0436
}